# Set pipeline name.
name: CI

# Set pipeline triggers.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# Define pipeline jobs.
jobs:
  # Build library, run on latest Ubuntu runner.
  build-library:
    name: Build library
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Build
        run: bash ci/build.sh

  # Check code formatting, run on latest Ubuntu runner.
  format-check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install clang-format
        run: sudo apt-get update && sudo apt-get install -y clang-format
      - name: Check formatting
        run: bash ci/format.sh --check
